name: core
description: "Capa core compartida: errores, resultado, utilidades, network, performance."
publish_to: "none"
resolution: workspace
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Notifications
  bot_toast: ^4.1.3

  # State Management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1

  # HTTP
  dio: ^5.9.1
  dio_http_formatter: ^3.3.1
  dio_cache_interceptor: ^4.0.5

  # Local Storage â€“ Drift
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.24
  sqlite3_web: ^0.1.1
  web: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.1

  # DI
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Utilities
  equatable: ^2.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.1.0
  injectable_generator: ^2.9.0
  json_serializable: ^6.11.0
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true
