name: feature_settings
description: "Feature de configuraci√≥n de la app."
publish_to: "none"
resolution: workspace
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  design_system:
    path: ../../design_system

  # Navigation
  go_router: ^17.1.0

  # i18n
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
